//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadUnidadEntrenamiento
    {
        public int IdActividadUnidadEntrenamiento { get; set; }
        public string AcuerdoObjetivos { get; set; }
        public string MediosEntrenamientos { get; set; }
        public string DesarrolloEntrenamientos { get; set; }
        public string ObjetivosMultiples { get; set; }
        public string MaterialAdecuado { get; set; }
        public string CompoentesEntrenamientos { get; set; }
        public string PlanificaActividadFinal { get; set; }
        public string EvaluaCumplimientoUE { get; set; }
        public string ObjetivosActividadFinal { get; set; }
        public string MotivacionObjetivos { get; set; }
        public string DisciplinaAdecuada { get; set; }
        public string ControlGrupo { get; set; }
        public string RespetoEntrenamiento { get; set; }
        public string RecomendacionesGenerales { get; set; }
        public string ObservacionesEntrenadores { get; set; }
        public string FirmaEntrenador { get; set; }
        public string FirmaMetodologo { get; set; }
        public Nullable<int> IdUnidadEntrenamiento { get; set; }

        public virtual UnidadEntrenamiento UnidadEntrenamiento { get; set; } = new UnidadEntrenamiento();
    }
}
