//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalisisMacrociclo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnalisisMacrociclo()
        {
            this.ObjetivosMacrociclo = new HashSet<ObjetivosMacrociclo>();
            this.PlanAnalisisMacro = new HashSet<PlanAnalisisMacro>();
        }
    
        public int IdMacroAnterior { get; set; }
        public Nullable<long> NumIdentificacionDeportist { get; set; }
        public string NombreDeportist { get; set; }
        public string Entrenador { get; set; }
        public string Deporte { get; set; }
        public string Agrupacion { get; set; }
        public string Categoria { get; set; }
        public string Modalidad { get; set; }
        public string Genero { get; set; }
        public string Año { get; set; }
        public string Mes { get; set; }
        public string Metodologo { get; set; }
        public Nullable<System.DateTime> FechaEvaluacion { get; set; }
        public string ObjetivoGeneral { get; set; }
        public string ObjetivosEspecificos { get; set; }
        public string PreparacionFisica { get; set; }
        public string PreparacionTecnica { get; set; }
        public string PreparacionTactica { get; set; }
        public string ResultadosCompetencia { get; set; }
        public string PronosticoMacrociclo { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjetivosMacrociclo> ObjetivosMacrociclo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanAnalisisMacro> PlanAnalisisMacro { get; set; }
    }
}
