//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsesoriasEntrenadores
    {
        public int IdAsesoriasEntrenadores { get; set; }
        public Nullable<long> NumIdentificacionDeportistas { get; set; }
        public string Deportista { get; set; }
        public string Entrenador { get; set; }
        public string Metodologo { get; set; }
        public string Deporte { get; set; }
        public string Agrupacion { get; set; }
        public string Escenarios { get; set; }
        public Nullable<System.DateTime> FechaAsesorias { get; set; }
        public string TemasAsesorias { get; set; }
        public string DesarrolloAsesorias { get; set; }
        public string ConclusionesAsesorias { get; set; }
        public string CompromisosAsesorias { get; set; }
        public string Asistentes { get; set; }
        public string FirmaEntrenador { get; set; }
        public string FirmaMetodologo { get; set; }
        public string UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
