//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CronogramaActividades
    {
        public int IdCronogramaActividadesSemanales { get; set; }
        public string EntrenadorActividadesSemanales { get; set; }
        public string DeporteActividadesSemanales { get; set; }
        public Nullable<System.DateTime> SemanadelActividadesSemanales { get; set; }
        public Nullable<System.DateTime> SemanaHastaActividadesSemanales { get; set; }
        public string ActividadActividadesSemanales { get; set; }
        public Nullable<System.TimeSpan> HoraActividadesSemanales { get; set; }
        public string LugarActividadesSemanales { get; set; }
        public Nullable<System.DateTime> FechaActividadesSemanales { get; set; }
        public string EventoActividadesSemanales { get; set; }
        public string VisitaBiomedicoActividadesSemanales { get; set; }
        public string FirmaEntrenador { get; set; }
        public string Usuarioregistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
