//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuadroMedallero
    {
        public int IdCuadroMedallero { get; set; }
        public string DeporteMedallero { get; set; }
        public string MedallaOro { get; set; }
        public string MedallaPlata { get; set; }
        public string MedallaBronce { get; set; }
        public string CategoriaMedallero { get; set; }
        public string DeportistaMedallero { get; set; }
        public string EventoMedallero { get; set; }
        public Nullable<System.DateTime> FechaMedallero { get; set; }
        public string PruebaMedallero { get; set; }
        public string Marca { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
