//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosFamiliares
    {
        public int IdFamiliares { get; set; }
        public string NomMadre { get; set; }
        public string ApeMadre { get; set; }
        public string Direccion { get; set; }
        public string Barrio { get; set; }
        public string Celular { get; set; }
        public string Ocupacion { get; set; }
        public string NomPadre { get; set; }
        public string ApePadre { get; set; }
        public string DireccionPadre { get; set; }
        public string BarrioPadre { get; set; }
        public string CelularPadre { get; set; }
        public string OcupacionPadre { get; set; }
        public string MarcaTorneos { get; set; }
        public string LugarTorneos { get; set; }
        public Nullable<System.DateTime> FechaTorneros { get; set; }
        public string EventosTorneos { get; set; }
        public string EntrenadorActual { get; set; }
        public string EmailEntrenador { get; set; }
        public string TelefonoEntrenador { get; set; }
        public string LugarEntrenamientoEntrenador { get; set; }
        public string HorasEntrenamiento { get; set; }
        public string DiasEntrenamiento { get; set; }
        public string ObservacionesEntrenamiento { get; set; }
        public Nullable<int> IdDeportista { get; set; }

        public virtual Deportistas Deportistas { get; set; } = new Deportistas();
    }
}
