//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deportistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deportistas()
        {
            this.DatosFamiliares = new HashSet<DatosFamiliares>();
            this.Ocupacion = new HashSet<Ocupacion>();
        }
    
        public int IdDeportista { get; set; }
        public string TipoIdentificacion { get; set; }
        public Nullable<long> NumIdentificacion { get; set; }
        public string EstadoDeportista { get; set; }
        public string ProgramaDeportista { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Imagen { get; set; }
        public string Edad { get; set; }
        public string Genero { get; set; }
        public string EpsDeportista { get; set; }
        public string GrupoSanguineo { get; set; }
        public string CorreoDeportista { get; set; }
        public string Deporte { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string PaisNacimiento { get; set; }
        public string DepartamentoNacimiento { get; set; }
        public string MunicipioNacimiento { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoMovil { get; set; }
        public string Pasaporte { get; set; }
        public string MunicipioResidencia { get; set; }
        public string BarrioResidencia { get; set; }
        public string DireccionResidencia { get; set; }
        public string EstadoCivil { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosFamiliares> DatosFamiliares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocupacion> Ocupacion { get; set; }
    }
}
