//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrenadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entrenadores()
        {
            this.EstudiosEntrenadores = new HashSet<EstudiosEntrenadores>();
        }
    
        public int IdEntrenadores { get; set; }
        public string TipoIdentificacionEntrenador { get; set; }
        public Nullable<long> NumeroIdentificacionEntrenador { get; set; }
        public string EstadoEntrenador { get; set; }
        public string PrimerNombreEntrenador { get; set; }
        public string SegundoNombreEntrenador { get; set; }
        public string PrimerApellidoEntrenador { get; set; }
        public string Segundoapellidoentrenador { get; set; }
        public string GeneroEntrenador { get; set; }
        public string GrupoSanguineoEntrenador { get; set; }
        public string EpsEntrenador { get; set; }
        public string CorreoEntrenador { get; set; }
        public Nullable<System.DateTime> FechaNacimientoEntrenador { get; set; }
        public string DeporteEntrenador { get; set; }
        public string NivelEstudioEntrenador { get; set; }
        public string TelefonoEntrenador { get; set; }
        public string DireccionEntrenador { get; set; }
        public string BarrioEntrenador { get; set; }
        public string EstadoCivilEntrenador { get; set; }
        public string EdadEntrenador { get; set; }
        public string Imagen { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudiosEntrenadores> EstudiosEntrenadores { get; set; }
    }
}
