//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudiosEntrenadores
    {
        public int IdEstudiosEntrenador { get; set; }
        public string EstudiosEntrenador { get; set; }
        public string CursosEntrenador { get; set; }
        public string RecordsEntrenador { get; set; }
        public string InvestigacionesEntrenador { get; set; }
        public string LibrosEntrenadores { get; set; }
        public string ExperienciasEntrenador { get; set; }
        public string AñosExperienciaEntrenador { get; set; }
        public string ClubDeportivoEntrenador { get; set; }
        public Nullable<int> IdEntrenadores { get; set; }

        public virtual Entrenadores Entrenadores { get; set; } = new Entrenadores();
    }
}
