//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioEntrenadores
    {
        public int IdHorarioEntrenadores { get; set; }
        public string DeporteHorarioEntrenadores { get; set; }
        public string EscenariosHorarioEntrenadores { get; set; }
        public string EntrenadorHorarioEntrenadores { get; set; }
        public string TelefonoHorarioEntrenadores { get; set; }
        public Nullable<System.TimeSpan> HoraInicioHorarioEntrenadores { get; set; }
        public Nullable<System.TimeSpan> HoraFinalHorarioEntrenadores { get; set; }
        public Nullable<System.DateTime> FechaHorEntrenadores { get; set; }
        public string FirmaEntrenador { get; set; }
        public string UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
