//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesociclo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mesociclo()
        {
            this.MesocicloDatos = new HashSet<MesocicloDatos>();
        }
    
        public int IdMesociclo { get; set; }
        public string Deporte { get; set; }
        public string Deportista { get; set; }
        public string Agrupacion { get; set; }
        public string Categoria { get; set; }
        public string Mesociclo1 { get; set; }
        public string TipoMesociclo { get; set; }
        public string Microciclo { get; set; }
        public string ObjetivosFisicos { get; set; }
        public string ObjetivosTacticos { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string FirmaEntrenador { get; set; }
        public string UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesocicloDatos> MesocicloDatos { get; set; }
    }
}
