//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIOMEDICOEntities5 : DbContext
    {
        public BIOMEDICOEntities5()
            : base("name=BIOMEDICOEntities5")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASignarPermisos> ASignarPermisos { get; set; }
        public virtual DbSet<Deporte> Deporte { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoPermiso> TipoPermiso { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<DatosFamiliares> DatosFamiliares { get; set; }
        public virtual DbSet<Deportistas> Deportistas { get; set; }
        public virtual DbSet<Ocupacion> Ocupacion { get; set; }
        public virtual DbSet<Entrenadores> Entrenadores { get; set; }
        public virtual DbSet<EstudiosEntrenadores> EstudiosEntrenadores { get; set; }
        public virtual DbSet<ActividadUnidadEntrenamiento> ActividadUnidadEntrenamiento { get; set; }
        public virtual DbSet<AsesoriasEntrenadores> AsesoriasEntrenadores { get; set; }
        public virtual DbSet<EvaluacionEquipoVisitaCompetencia> EvaluacionEquipoVisitaCompetencia { get; set; }
        public virtual DbSet<EvaluacionVisitaCompetencia> EvaluacionVisitaCompetencia { get; set; }
        public virtual DbSet<PlanEntrenamientoMensual> PlanEntrenamientoMensual { get; set; }
        public virtual DbSet<UnidadEntrenamiento> UnidadEntrenamiento { get; set; }
        public virtual DbSet<VisitaCompetencias> VisitaCompetencias { get; set; }
        public virtual DbSet<AnalisisMacrociclo> AnalisisMacrociclo { get; set; }
        public virtual DbSet<ObjetivosMacrociclo> ObjetivosMacrociclo { get; set; }
        public virtual DbSet<PlanAnalisisMacro> PlanAnalisisMacro { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CronogramaActividades> CronogramaActividades { get; set; }
        public virtual DbSet<Elemento> Elemento { get; set; }
        public virtual DbSet<Microciclo> Microciclo { get; set; }
        public virtual DbSet<GymColiseo> GymColiseo { get; set; }
        public virtual DbSet<GymEstadio> GymEstadio { get; set; }
        public virtual DbSet<HorarioEntrenadores> HorarioEntrenadores { get; set; }
        public virtual DbSet<UnidadMesociclo> UnidadMesociclo { get; set; }
        public virtual DbSet<Mesociclo> Mesociclo { get; set; }
        public virtual DbSet<MesocicloDatos> MesocicloDatos { get; set; }
        public virtual DbSet<PlanSemanalDias> PlanSemanalDias { get; set; }
        public virtual DbSet<PlanSemanalMicrociclo> PlanSemanalMicrociclo { get; set; }
        public virtual DbSet<PlanGrafico> PlanGrafico { get; set; }
        public virtual DbSet<PlanGraficoDatos> PlanGraficoDatos { get; set; }
        public virtual DbSet<RolDeporte> RolDeporte { get; set; }
        public virtual DbSet<CuadroMedallero> CuadroMedallero { get; set; }
    }
}
