//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetivosMacrociclo
    {
        public int IdObjetivosMacrociclo { get; set; }
        public string ObjetivosHumanos { get; set; }
        public string ObjetivosFisicos { get; set; }
        public string ObjetivosFinancieros { get; set; }
        public string ObjetivosDeportivos { get; set; }
        public string MedicinaDelDeporte { get; set; }
        public string MesocicloHumano { get; set; }
        public string MesocicloFisico { get; set; }
        public string MesocicloFinanciero { get; set; }
        public string MesocicloDeportivo { get; set; }
        public string MesocicloDeporte { get; set; }
        public string PropuestoHumano { get; set; }
        public string PropuestoFisico { get; set; }
        public string PropuestoFinanciero { get; set; }
        public string PropuestoDeportivo { get; set; }
        public string PropuestoDeporte { get; set; }
        public string DistribucionMacrociclo { get; set; }
        public string PreparacionMacrociclo { get; set; }
        public string CompetenciaMacrociclo { get; set; }
        public string DiasTrabajoMacrociclo { get; set; }
        public string OtrosDiasMacrociclo { get; set; }
        public string AcumulacionMacrociclo { get; set; }
        public string TransformacionMacrocilo { get; set; }
        public string RealizacionMacrociclo { get; set; }
        public Nullable<int> IdMacroAnterior { get; set; }
    
        public virtual AnalisisMacrociclo AnalisisMacrociclo { get; set; } = new AnalisisMacrociclo();
    }
}
