//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocupacion
    {
        public int IdOcupacion { get; set; }
        public string NivelEducativo { get; set; }
        public string OperacionesDepor { get; set; }
        public string CualOperacion { get; set; }
        public string FracturasDepor { get; set; }
        public string CualFractura { get; set; }
        public string LesionesDepor { get; set; }
        public string CualLesion { get; set; }
        public string AlergiasDepor { get; set; }
        public string CualAlergia { get; set; }
        public string EspecialidadCombate { get; set; }
        public string AñosActivos { get; set; }
        public string ClubDeportivo { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Estatura { get; set; }
        public string TallaCamisa { get; set; }
        public Nullable<int> TallaPantalon { get; set; }
        public Nullable<int> TallaCalzado { get; set; }
        public string TallaSudadera { get; set; }
        public Nullable<int> NumeroHijos { get; set; }
        public Nullable<int> IdDeportista { get; set; }
    
        public virtual Deportistas Deportistas { get; set; } = new Deportistas();
    }
}
