//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanGraficoDatos
    {
        public int IdPlanGraficoDatos { get; set; }
        public string NombrePrincipal { get; set; }
        public string NombreElementoPlangrafico { get; set; }
        public string Ideal1 { get; set; }
        public string Ideal2 { get; set; }
        public string Ideal3 { get; set; }
        public string Ideal4 { get; set; }
        public string Ideal5 { get; set; }
        public string Ideal6 { get; set; }
        public string Ideal7 { get; set; }
        public string Ideal8 { get; set; }
        public string Ideal9 { get; set; }
        public string Ideal10 { get; set; }
        public string Ideal11 { get; set; }
        public string Ideal12 { get; set; }
        public string Ideal13 { get; set; }
        public string Ideal14 { get; set; }
        public string Ideal15 { get; set; }
        public string Ideal16 { get; set; }
        public Nullable<int> IdPlanGrafico { get; set; }

        public virtual PlanGrafico PlanGrafico { get; set; } = new PlanGrafico();
    }
}
