//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanSemanalMicrociclo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanSemanalMicrociclo()
        {
            this.PlanSemanalDias = new HashSet<PlanSemanalDias>();
        }
    
        public int IdPlanSemanal { get; set; }
        public string DeportePlan { get; set; }
        public string Deportista { get; set; }
        public string EntrenadorPlan { get; set; }
        public string Agrupacion { get; set; }
        public string Categoria { get; set; }
        public string MicroCicloNum { get; set; }
        public string TipoMicroCiclo { get; set; }
        public string MesoCiclo { get; set; }
        public string TipoMesociclo { get; set; }
        public string ObjetivosFisicos { get; set; }
        public string ObjetivosTecnicos { get; set; }
        public string ElementosMicrociclo { get; set; }
        public Nullable<System.DateTime> FechaMicrociclo { get; set; }
        public Nullable<System.TimeSpan> HoraInicioPlan { get; set; }
        public Nullable<System.TimeSpan> HoraFinalPlan { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanSemanalDias> PlanSemanalDias { get; set; }
    }
}
