//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanEntrenamientoMensual
    {
        public int IdPlanEntrenamientoMensual { get; set; }
        public Nullable<long> NumIdentificacionDeportista { get; set; }
        public string NombreDeportista { get; set; }
        public string Entrenador { get; set; }
        public string Deporte { get; set; }
        public string Agrupacion { get; set; }
        public string Categoria { get; set; }
        public string Modalidad { get; set; }
        public string Mes { get; set; }
        public string Año { get; set; }
        public string Metodologo { get; set; }
        public string FechaEntregaActa { get; set; }
        public string Preparacionfisica { get; set; }
        public string PreparacionTecnica { get; set; }
        public string PreparacionTactica { get; set; }
        public string ObjetivosParciales { get; set; }
        public string FirmaEntrenador { get; set; }
        public string FirmaMetodologo { get; set; }
        public string UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistra { get; set; }
    }
}
