//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanGrafico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanGrafico()
        {
            this.PlanGraficoDatos = new HashSet<PlanGraficoDatos>();
        }
    
        public int IdPlanGrafico { get; set; }
        public string Deporte { get; set; }
        public string NombreMacrociclo { get; set; }
        public string Mes1 { get; set; }
        public string Mes2 { get; set; }
        public string Mes3 { get; set; }
        public string mes4 { get; set; }
        public string Mesociclos1 { get; set; }
        public string Mesociclos2 { get; set; }
        public string Mesociclos3 { get; set; }
        public string Mesociclos4 { get; set; }
        public string NumeroMicrociclo1 { get; set; }
        public string NumeroMicrociclo2 { get; set; }
        public string NumeroMicrociclo3 { get; set; }
        public string NumeroMicrociclo4 { get; set; }
        public string NumeroMicrociclo5 { get; set; }
        public string NumeroMicrociclo6 { get; set; }
        public string NumeroMicrociclo7 { get; set; }
        public string NumeroMicrociclo8 { get; set; }
        public string NumeroMicrociclo9 { get; set; }
        public string NumeroMicrociclo10 { get; set; }
        public string NumeroMicrociclo11 { get; set; }
        public string NumeroMicrociclo12 { get; set; }
        public string NumeroMicrociclo13 { get; set; }
        public string NumeroMicrociclo14 { get; set; }
        public string NumeroMicrociclo15 { get; set; }
        public string NumeroMicrociclo16 { get; set; }
        public string TipoMicrociclo1 { get; set; }
        public string TipoMicrociclo2 { get; set; }
        public string TipoMicrociclo3 { get; set; }
        public string TipoMicrociclo4 { get; set; }
        public string TipoMicrociclo5 { get; set; }
        public string TipoMicrociclo6 { get; set; }
        public string TipoMicrociclo7 { get; set; }
        public string TipoMicrociclo8 { get; set; }
        public string TipoMicrociclo9 { get; set; }
        public string TipoMicrociclo10 { get; set; }
        public string TipoMicrociclo11 { get; set; }
        public string TipoMicrociclo12 { get; set; }
        public string TipoMicrociclo13 { get; set; }
        public string TipoMicrociclo14 { get; set; }
        public string TipoMicrociclo15 { get; set; }
        public string TipoMicrociclo16 { get; set; }
        public string FechaMesUno { get; set; }
        public string FechaMesUno2 { get; set; }
        public string FechaMesUno3 { get; set; }
        public string FechaMesUno4 { get; set; }
        public string FechaMesUno5 { get; set; }
        public string FechaMesUno6 { get; set; }
        public string FechaMesUno7 { get; set; }
        public string FechaMesUno8 { get; set; }
        public string FechaMesDos { get; set; }
        public string FechaMesDos2 { get; set; }
        public string FechaMesDos3 { get; set; }
        public string FechaMesDos4 { get; set; }
        public string FechaMesDos5 { get; set; }
        public string FechaMesDos6 { get; set; }
        public string FechaMesDos7 { get; set; }
        public string FechaMesDos8 { get; set; }
        public string FechaMesTres { get; set; }
        public string FechaMesTres2 { get; set; }
        public string FechaMesTres3 { get; set; }
        public string FechaMesTres4 { get; set; }
        public string FechaMesTres5 { get; set; }
        public string FechaMesTres6 { get; set; }
        public string FechaMesTres7 { get; set; }
        public string FechaMesTres8 { get; set; }
        public string FechaMesCuatro { get; set; }
        public string FechaMesCuatro2 { get; set; }
        public string FechaMesCuatro3 { get; set; }
        public string FechaMesCuatro4 { get; set; }
        public string FechaMesCuatro5 { get; set; }
        public string FechaMesCuatro6 { get; set; }
        public string FechaMesCuatro7 { get; set; }
        public string FechaMesCuatro8 { get; set; }
        public string NumeroSesiones { get; set; }
        public string NumeroSesiones2 { get; set; }
        public string NumeroSesiones3 { get; set; }
        public string NumeroSesiones4 { get; set; }
        public string NumeroSesiones5 { get; set; }
        public string NumeroSesiones6 { get; set; }
        public string NumeroSesiones7 { get; set; }
        public string NumeroSesiones8 { get; set; }
        public string NumeroSesiones9 { get; set; }
        public string NumeroSesiones10 { get; set; }
        public string NumeroSesiones11 { get; set; }
        public string NumeroSesiones12 { get; set; }
        public string NumeroSesiones13 { get; set; }
        public string NumeroSesiones14 { get; set; }
        public string NumeroSesiones15 { get; set; }
        public string NumeroSesiones16 { get; set; }
        public string FirmaEntrenador { get; set; }
        public string FirmaMetodologo { get; set; }
        public string UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanGraficoDatos> PlanGraficoDatos { get; set; }
    }
}
