//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadEntrenamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnidadEntrenamiento()
        {
            this.ActividadUnidadEntrenamiento = new HashSet<ActividadUnidadEntrenamiento>();
        }
    
        public int IdUnidadEntrenamiento { get; set; }
        public string NombreEntrenador { get; set; }
        public string Deporte { get; set; }
        public string Agrupacion { get; set; }
        public string Categoria { get; set; }
        public string Modalidad { get; set; }
        public Nullable<System.DateTime> FechaSesion { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFinal { get; set; }
        public string ObjetivosSesion { get; set; }
        public string NumMesociclo { get; set; }
        public string TipoMicrociclo { get; set; }
        public string MetodologoEvaluador { get; set; }
        public string Sesionentrenamiento { get; set; }
        public string UnidadEntrenamiento1 { get; set; }
        public string ObjetivosEntrenamiento { get; set; }
        public string PlanificaCalentamiento { get; set; }
        public string CalentamientoGeneral { get; set; }
        public string CalentamientoEspecifico { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadUnidadEntrenamiento> ActividadUnidadEntrenamiento { get; set; }
    }
}
