//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadMesociclo
    {
        public int IdUnidadMesociclo { get; set; }
        public string NombreUnidadMesociclo { get; set; }
        public string DeportistUnidadMesociclo { get; set; }
        public string AgrupacionUnidadMesociclo { get; set; }
        public string CategoriaUnidadMesociclo { get; set; }
        public string Mesociclo { get; set; }
        public string TipoMesociclo { get; set; }
        public string Miclociclo { get; set; }
        public string SesionesEntrenamientos { get; set; }
        public string Duracion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public string Objetivos { get; set; }
        public string CapacidadInicial { get; set; }
        public string CapacidadControl { get; set; }
        public string CapacidadFinal { get; set; }
        public string ActividadInicial { get; set; }
        public string ActividadControl { get; set; }
        public string ActividadFinal { get; set; }
        public string MetodoInicial { get; set; }
        public string MetodoControl { get; set; }
        public string Metodofinal { get; set; }
        public string DosificacionInicial { get; set; }
        public string DosificacionControl { get; set; }
        public string DosificacionFinal { get; set; }
        public string FirmaEntrenador { get; set; }
        public string Usuarioregistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
