//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitaCompetencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitaCompetencias()
        {
            this.EvaluacionEquipoVisitaCompetencia = new HashSet<EvaluacionEquipoVisitaCompetencia>();
            this.EvaluacionVisitaCompetencia = new HashSet<EvaluacionVisitaCompetencia>();
        }
    
        public int IdVisitaCompetencia { get; set; }
        public string TorneoVisitaCompetencia { get; set; }
        public Nullable<System.DateTime> FechaInicioEvento { get; set; }
        public Nullable<System.DateTime> FechaFinalEvento { get; set; }
        public Nullable<System.DateTime> FechaSalidaEvento { get; set; }
        public Nullable<System.DateTime> FechaRegresoEvento { get; set; }
        public string EquipoDeportista { get; set; }
        public string DeporteVisitaCompetencia { get; set; }
        public string CategoriaVisitaCompetencia { get; set; }
        public string AgrupacionVisitaCompetencia { get; set; }
        public string EntrenadorVisitaCompetencia { get; set; }
        public string NumeroEquiposVisitaCompetencia { get; set; }
        public string AsistentesEventoVisitaCompetencia { get; set; }
        public string TecnicosEventoVisitaCompetencia { get; set; }
        public string SistemaCompetenciaVisitaCompetencia { get; set; }
        public string CombatesVisitaCompetencia { get; set; }
        public string SemifinalFinalVisitaCompetencia { get; set; }
        public string MedalleroDeportista { get; set; }
        public string MedallaOroDeportista { get; set; }
        public string MedallaPlataDeportista { get; set; }
        public string MedallaBronceDeportista { get; set; }
        public string MedalleroEquipo { get; set; }
        public string MedallaOroEquipo { get; set; }
        public string MedallaPlataEquipo { get; set; }
        public string MedallaBronceEquipo { get; set; }
        public string ObservacionesPositivas { get; set; }
        public string ObservacionesNegativas { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionEquipoVisitaCompetencia> EvaluacionEquipoVisitaCompetencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionVisitaCompetencia> EvaluacionVisitaCompetencia { get; set; }
    }
}
